version: '3.9'

services:
  pisaude-backend:
    build: .
    container_name: pisaude-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads  # âœ… NOVO VOLUME ADICIONADO
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - pisaude-db

  pisaude-db:
    image: postgres:15
    container_name: pisaude-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pisaude
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
